[package]
name = "gamekit"
version = "0.1.0"
authors = ["Nazarí González <nazari.nz@gmail.com>"]
edition = "2021"
categories = ["game-engines", "game-development"]
keywords = ["notan", "game", "engine", "gamedev", "2d"]
readme = "README.md"
homepage = "https://github.com/Nazariglez/gamekit"
repository = "https://github.com/Nazariglez/gamekit"
license = "MIT OR Apache-2.0"
description = "A set of helpers for making games with notan"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
lto = true

[workspace]
members = ["crates/*"]

[workspace.dependencies]
gk_app = { path = "./crates/gk_app", version = "0.1.0" }

serde = { version = "1.0", features = ["serde_derive"] }
log = "0.4.19"
hashbrown = "0.14.0"

[dependencies]
anymap = "0.12.1"
# default-features=false...
notan = { version = "0.9.3" }
