[package]
name = "gk_assets"
version = "0.1.0"
edition = "2021"

[dependencies]
gk_app.workspace = true

log.workspace = true
parking_lot.workspace = true
hashbrown.workspace = true

futures = "0.3.28"
futures-util = { version = "0.3.28", default-features = false }
platter2 = "0.1.6"
